(iOS) Fix keyboardAppearance in dark mode
talkjs/flutter_inappwebview pull request #2
Opened 2023-08-10 23:08 UTC by moubaraks

Fixes the keyboard's dark mode appearance

2023-08-14 05:09 UTC, bugnano requested changes
Just one thing: Instead of merging this PR into `master`, you should merge it into the `non_beta_build` branch instead.

2023-08-14 12:20 UTC, vickz84259 requested changes
The change currently switches keyboard appearance based on the OS's appearance setting. However the OS already does this by default. The change needs to use whatever theme appearance the app is currently using since most apps allow their users to explicitly choose dark or light or for it to use the current system setting.

2023-08-14 12:20 UTC, vickz84259 commented on lib/src/in_app_webview/in_app_webview.dart
> +          'keyboardAppearanceDark': MediaQuery.platformBrightnessOf(context) == Brightness.dark,
I've tested the change and it doesn't fix the issue highlighted [here](https://github.com/talkjs/talkjs-flutter/issues/24). Here are steps to reproduce:

1. Inside `main.dart` add theme: `ThemeData.dark()` to `MaterialApp`'s constructor.
2. Make sure the iPhone's appearance setting under display & brightness is set to light
3. Run app. The app will be in dark mode but the keyboard will still be the light mode version.

By default, the iOS keyboard switches between light and dark mode in respective to the current appearance setting in Settings. So using `MediaQuery.platformBrightnessOf` doesn't fix the issue. Instead use `Theme.of` to determine the current theme the app is in and choose the light or dark keyboard appearance accordingly.

2023-08-14 15:35 UTC, moubaraks commented on lib/src/in_app_webview/in_app_webview.dart
> +          'keyboardAppearanceDark': MediaQuery.platformBrightnessOf(context) == Brightness.dark,
Fixed

2023-08-17 08:56 UTC, vickz84259 reviewed
Awesome work @moubaraks.

2023-08-17 09:24 UTC, merged